"use client";
import "./globals.css";
import { AppCustomContextProvider } from "./utils/context";
import { Toaster } from "react-hot-toast";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AppCustomContextProvider>
        <body className="">
          <Toaster />
          {children}
        </body>
      </AppCustomContextProvider>
    </html>
  );
}
